import type {
  DataPluginMergeRequest,
  DataPluginMergeRequests,
} from '../../../../interfaces/dataPluginInterfaces/dataPluginMergeRequests.ts';

export default class MergeRequests implements DataPluginMergeRequests {
  constructor() {}

  // this mock data is far from complete and could be more useful
  public async getAll(from: string, to: string): Promise<DataPluginMergeRequest[]> {
    console.log(`Getting Merge Requests from ${from} to ${to}`);
    return new Promise<DataPluginMergeRequest[]>((resolve) => {
      const Tester1 = {
        id: '1',
        name: 'Tester 1',
        platform: 'GitHub',
        user: {
          id: '1',
          gitSignature: 'tester@github.com',
          account: null,
        },
      };

      const Tester2 = {
        id: '2',
        name: 'Tester 2',
        platform: 'GitHub',
        user: {
          id: '2',
          gitSignature: 'tester2@github.com',
          account: null,
        },
      };

      const mergeRequests: DataPluginMergeRequest[] = [
        {
          id: '1',
          iid: 101,
          title: 'Fix login issue',
          state: 'OPENED',
          webUrl: 'https://github.com/project/mr/101',
          createdAt: '2025-06-01T10:00:00Z',
          closedAt: null,
          updatedAt: '2025-06-01T10:00:00Z',
          sourceBranch: 'bugfix/login',
          targetBranch: 'main',
          author: Tester1,
          assignee: Tester2,
          assignees: [Tester2],
          notes: [],
        },
        {
          id: '2',
          iid: 102,
          title: 'Add API documentation',
          state: 'MERGED',
          webUrl: 'https://github.com/project/mr/102',
          createdAt: '2025-08-02T09:15:00Z',
          closedAt: '2025-08-03T09:15:00Z',
          updatedAt: '2025-08-03T09:15:00Z',
          sourceBranch: 'docs/api',
          targetBranch: 'main',
          author: Tester2,
          assignee: Tester1,
          assignees: [Tester1],
          notes: [],
        },
        {
          id: '3',
          iid: 103,
          title: 'Improve search performance',
          state: 'OPENED',
          webUrl: 'https://github.com/project/mr/103',
          createdAt: '2025-07-25T08:30:00Z',
          closedAt: null,
          updatedAt: '2025-07-25T08:30:00Z',
          sourceBranch: 'perf/search',
          targetBranch: 'main',
          author: Tester1,
          assignee: Tester2,
          assignees: [Tester2],
          notes: [],
        },
        {
          id: '4',
          iid: 104,
          title: 'Refactor authentication module',
          state: 'MERGED',
          webUrl: 'https://github.com/project/mr/104',
          createdAt: '2025-07-04T14:20:00Z',
          closedAt: '2025-07-05T14:20:00Z',
          updatedAt: '2025-07-05T14:20:00Z',
          sourceBranch: 'refactor/auth',
          targetBranch: 'main',
          author: Tester2,
          assignee: Tester1,
          assignees: [Tester1],
          notes: [],
        },
        {
          id: '5',
          iid: 105,
          title: 'Update UI styling',
          state: 'OPENED',
          webUrl: 'https://github.com/project/mr/105',
          createdAt: '2025-08-01T07:45:00Z',
          closedAt: null,
          updatedAt: '2025-08-01T07:45:00Z',
          sourceBranch: 'ui/update-styles',
          targetBranch: 'main',
          author: Tester1,
          assignee: Tester2,
          assignees: [Tester2],
          notes: [],
        },
        {
          id: '6',
          iid: 106,
          title: 'Fix typo in README',
          state: 'MERGED',
          webUrl: 'https://github.com/project/mr/106',
          createdAt: '2025-08-03T06:00:00Z',
          closedAt: '2025-08-04T06:00:00Z',
          updatedAt: '2025-08-04T06:00:00Z',
          sourceBranch: 'fix/readme-typo',
          targetBranch: 'main',
          author: Tester2,
          assignee: Tester1,
          assignees: [Tester1],
          notes: [],
        },
        {
          id: '7',
          iid: 107,
          title: 'Add unit tests for user service',
          state: 'OPENED',
          webUrl: 'https://github.com/project/mr/107',
          createdAt: '2025-08-07T11:50:00Z',
          closedAt: null,
          updatedAt: '2025-08-07T11:50:00Z',
          sourceBranch: 'test/user-service',
          targetBranch: 'main',
          author: Tester1,
          assignee: Tester2,
          assignees: [Tester2],
          notes: [],
        },
        {
          id: '8',
          iid: 108,
          title: 'Optimize image loading',
          state: 'MERGED',
          webUrl: 'https://github.com/project/mr/108',
          createdAt: '2025-08-08T09:40:00Z',
          closedAt: '2025-08-09T09:40:00Z',
          updatedAt: '2025-08-09T09:40:00Z',
          sourceBranch: 'perf/image-loading',
          targetBranch: 'main',
          author: Tester2,
          assignee: Tester1,
          assignees: [Tester1],
          notes: [],
        },
        {
          id: '9',
          iid: 109,
          title: 'Implement caching',
          state: 'CLOSED',
          webUrl: 'https://github.com/project/mr/109',
          createdAt: '2025-08-09T07:25:00Z',
          closedAt: '2025-08-10T07:25:00Z',
          updatedAt: '2025-08-10T07:25:00Z',
          sourceBranch: 'feature/caching',
          targetBranch: 'main',
          author: Tester1,
          assignee: Tester2,
          assignees: [Tester2],
          notes: [],
        },
        {
          id: '10',
          iid: 110,
          title: 'Update dependencies',
          state: 'CLOSED',
          webUrl: 'https://github.com/project/mr/110',
          createdAt: '2025-08-12T08:15:00Z',
          closedAt: '2025-08-13T08:15:00Z',
          updatedAt: '2025-08-13T08:15:00Z',
          sourceBranch: 'chore/update-deps',
          targetBranch: 'main',
          author: Tester2,
          assignee: Tester1,
          assignees: [Tester1],
          notes: [],
        },
      ];

      resolve(mergeRequests);
    });
  }
}
