import {
  DataPluginAccount,
  DataPluginAccounts,
} from "../../../interfaces/dataPluginInterfaces/dataPluginAccount.ts";

export default class AccountsIssues implements DataPluginAccounts {
  constructor() {}

  /**
   * Retrieves mock accounts with mock issues
   */
  public async getAll(): Promise<DataPluginAccount[]> {
    return new Promise<DataPluginAccount[]>((resolve) => {
      const accountsIssues: DataPluginAccount[] = [
        // 10 fully connected users
        {
          id: "user1",
          login: "user1",
          name: "User 1",
          avatarUrl: "https://example.com/avatar/user1.png",
          url: "https://example.com/user1",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user2",
          login: "user2",
          name: "User 2",
          avatarUrl: "https://example.com/avatar/user2.png",
          url: "https://example.com/user2",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user3",
          login: "user3",
          name: "User 3",
          avatarUrl: "https://example.com/avatar/user3.png",
          url: "https://example.com/user3",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user4",
          login: "user4",
          name: "User 4",
          avatarUrl: "https://example.com/avatar/user4.png",
          url: "https://example.com/user4",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user5",
          login: "user5",
          name: "User 5",
          avatarUrl: "https://example.com/avatar/user5.png",
          url: "https://example.com/user5",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user6",
          login: "user6",
          name: "User 6",
          avatarUrl: "https://example.com/avatar/user6.png",
          url: "https://example.com/user6",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user7",
          login: "user7",
          name: "User 7",
          avatarUrl: "https://example.com/avatar/user7.png",
          url: "https://example.com/user7",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user8",
          login: "user8",
          name: "User 8",
          avatarUrl: "https://example.com/avatar/user8.png",
          url: "https://example.com/user8",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user9",
          login: "user9",
          name: "User 9",
          avatarUrl: "https://example.com/avatar/user9.png",
          url: "https://example.com/user9",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user10",
          login: "user10",
          name: "User 10",
          avatarUrl: "https://example.com/avatar/user10.png",
          url: "https://example.com/user10",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        // 8 loosely connected users
        {
          id: "user11",
          login: "user11",
          name: "User 11",
          avatarUrl: "https://example.com/avatar/user11.png",
          url: "https://example.com/user11",
          issues: [
            {
              id: "ISSUE-L1",
              iid: "201",
              title: "Loose Cluster 1",
              description: "Links 11 & 12",
              createdAt: "2025-02-01T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/201",
            },
            {
              id: "ISSUE-L4",
              iid: "204",
              title: "Overlap Cluster A",
              description: "Links 11, 13, 17",
              createdAt: "2025-03-01T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/204",
            },
          ],
        },
        {
          id: "user12",
          login: "user12",
          name: "User 12",
          avatarUrl: "https://example.com/avatar/user12.png",
          url: "https://example.com/user12",
          issues: [
            {
              id: "ISSUE-L1",
              iid: "201",
              title: "Loose Cluster 1",
              description: "Links 11 & 12",
              createdAt: "2025-02-01T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/201",
            },
            {
              id: "ISSUE-L5",
              iid: "205",
              title: "Overlap Cluster B",
              description: "Links 12, 14, 18",
              createdAt: "2025-03-05T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/205",
            },
          ],
        },
        {
          id: "user13",
          login: "user13",
          name: "User 13",
          avatarUrl: "https://example.com/avatar/user13.png",
          url: "https://example.com/user13",
          issues: [
            {
              id: "ISSUE-L2",
              iid: "202",
              title: "Loose Cluster 2",
              description: "Links 13–15",
              createdAt: "2025-02-05T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/202",
            },
            {
              id: "ISSUE-L4",
              iid: "204",
              title: "Overlap Cluster A",
              description: "Links 11, 13, 17",
              createdAt: "2025-03-01T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/204",
            },
          ],
        },
        {
          id: "user14",
          login: "user14",
          name: "User 14",
          avatarUrl: "https://example.com/avatar/user14.png",
          url: "https://example.com/user14",
          issues: [
            {
              id: "ISSUE-L2",
              iid: "202",
              title: "Loose Cluster 2",
              description: "Links 13–15",
              createdAt: "2025-02-05T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/202",
            },
            {
              id: "ISSUE-L5",
              iid: "205",
              title: "Overlap Cluster B",
              description: "Links 12, 14, 18",
              createdAt: "2025-03-05T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/205",
            },
          ],
        },
        {
          id: "user15",
          login: "user15",
          name: "User 15",
          avatarUrl: "https://example.com/avatar/user15.png",
          url: "https://example.com/user15",
          issues: [
            {
              id: "ISSUE-L2",
              iid: "202",
              title: "Loose Cluster 2",
              description: "Links 13–15",
              createdAt: "2025-02-05T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/202",
            },
          ],
        },
        {
          id: "user16",
          login: "user16",
          name: "User 16",
          avatarUrl: "https://example.com/avatar/user16.png",
          url: "https://example.com/user16",
          issues: [
            {
              id: "ISSUE-L3",
              iid: "203",
              title: "Loose Cluster 3",
              description: "Links 16–18",
              createdAt: "2025-02-10T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/203",
            },
          ],
        },
        {
          id: "user17",
          login: "user17",
          name: "User 17",
          avatarUrl: "https://example.com/avatar/user17.png",
          url: "https://example.com/user17",
          issues: [
            {
              id: "ISSUE-L3",
              iid: "203",
              title: "Loose Cluster 3",
              description: "Links 16–18",
              createdAt: "2025-02-10T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/203",
            },
            {
              id: "ISSUE-L4",
              iid: "204",
              title: "Overlap Cluster A",
              description: "Links 11, 13, 17",
              createdAt: "2025-03-01T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/204",
            },
          ],
        },
        {
          id: "user18",
          login: "user18",
          name: "User 18",
          avatarUrl: "https://example.com/avatar/user18.png",
          url: "https://example.com/user18",
          issues: [
            {
              id: "ISSUE-L3",
              iid: "203",
              title: "Loose Cluster 3",
              description: "Links 16–18",
              createdAt: "2025-02-10T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/203",
            },
            {
              id: "ISSUE-L5",
              iid: "205",
              title: "Overlap Cluster B",
              description: "Links 12, 14, 18",
              createdAt: "2025-03-05T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/205",
            },
          ],
        },
        // 2 alone users
        {
          id: "user19",
          login: "user19",
          name: "User 19",
          avatarUrl: "https://example.com/avatar/user19.png",
          url: "https://example.com/user19",
          issues: [],
        },
        {
          id: "user20",
          login: "user20",
          name: "User 20",
          avatarUrl: "https://example.com/avatar/user20.png",
          url: "https://example.com/user20",
          issues: [],
        },
      ];
      resolve(accountsIssues);
    });
  }
}
