import {
  DataPluginAccount,
  DataPluginAccounts,
} from "../../../interfaces/dataPluginInterfaces/dataPluginAccount.ts";

export default class AccountsIssues implements DataPluginAccounts {
  constructor() {}

  /**
   * Retrieves mock accounts with mock issues
   */
  public async getAll(): Promise<DataPluginAccount[]> {
    return new Promise<DataPluginAccount[]>((resolve) => {
      //Scenario A: Isolated Members in Small Teams
      const scenario_a = [
        {
          id: "alice",
          login: "alice",
          name: "Alice",
          avatarUrl:
            "https://ui-avatars.com/api/?name=Alice&background=random&color=fff",
          url: "https://example.com/alice",
          issues: [
            {
              id: "1",
              iid: "1",
              title: "UI Bug",
              description: "",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-01-01T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/1",
            },
            {
              id: "2",
              iid: "2",
              title: "Refactor",
              description: "",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-01-02T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/2",
            },
            {
              id: "3",
              iid: "3",
              title: "UI Bug",
              description: "",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-01-01T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/1",
            },
            {
              id: "4",
              iid: "4",
              title: "Refactor",
              description: "",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-01-02T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/2",
            },
          ],
        },
        {
          id: "bob",
          login: "bob",
          name: "Bob",
          avatarUrl:
            "https://ui-avatars.com/api/?name=Bob&background=random&color=fff",
          url: "https://example.com/bob",
          issues: [
            {
              id: "1",
              iid: "1",
              title: "UI Bug",
              description: "",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-01-01T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/1",
            },
            {
              id: "2",
              iid: "2",
              title: "Refactor",
              description: "",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-01-02T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/2",
            },
            {
              id: "3",
              iid: "3",
              title: "UI Bug",
              description: "",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-01-01T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/1",
            },
            {
              id: "4",
              iid: "4",
              title: "Refactor",
              description: "",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-01-02T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/2",
            },
          ],
        },
        {
          id: "carol",
          login: "carol",
          name: "Carol",
          avatarUrl:
            "https://ui-avatars.com/api/?name=Carol&background=random&color=fff",
          url: "https://example.com/carol",
          issues: [
            {
              id: "2",
              iid: "2",
              title: "Refactor",
              description: "",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-01-02T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/2",
            },
            {
              id: "3",
              iid: "3",
              title: "UI Bug",
              description: "",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-01-01T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/1",
            },
            {
              id: "5",
              iid: "5",
              title: "Refactor",
              description: "",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-01-02T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/2",
            },
          ],
        },
        {
          id: "dave",
          login: "dave",
          name: "Dave",
          avatarUrl:
            "https://ui-avatars.com/api/?name=Dave&background=random&color=fff",
          url: "https://example.com/dave",
          issues: [
            {
              id: "5",
              iid: "5",
              title: "Refactor",
              description: "",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-01-02T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/2",
            },
          ],
        },
        {
          id: "eve",
          login: "eve",
          name: "Eve",
          avatarUrl:
            "https://ui-avatars.com/api/?name=Eve&background=random&color=fff",
          url: "https://example.com/eve",
          issues: [],
        },
      ];

      const scenario_b = [
        // Frontend team
        ...["Fiona", "Frank", "Faith", "Felix", "Freya"].map((name) => ({
          id: name.toLowerCase(),
          login: name.toLowerCase(),
          name,
          avatarUrl: `https://ui-avatars.com/api/?name=${name}&background=random&color=fff`,
          url: `https://example.com/${name.toLowerCase()}`,
          issues: [
            {
              id: "FE-ISSUE-1",
              iid: "1001",
              title: "Frontend: Layout Overhaul",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-01-10T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/1001",
            },
            {
              id: "FE-ISSUE-2",
              iid: "1002",
              title: "Frontend: Component Styling",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-01-11T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/1002",
            },
            {
              id: "FE-ISSUE-3",
              iid: "1003",
              title: "Frontend: UI Testing",
              createdAt: "2025-01-03T00:00:00.000Z",
              closedAt: "2025-01-12T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/1003",
            },
          ],
        })),

        // Backend team
        ...["Brian", "Bianca", "Boris", "Bella", "Ben"].map((name) => ({
          id: name.toLowerCase(),
          login: name.toLowerCase(),
          name,
          avatarUrl: `https://ui-avatars.com/api/?name=${name}&background=random&color=fff`,
          url: `https://example.com/${name.toLowerCase()}`,
          issues: [
            {
              id: "BE-ISSUE-1",
              iid: "2001",
              title: "Backend: API Design",
              createdAt: "2025-01-04T00:00:00.000Z",
              closedAt: "2025-01-13T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/2001",
            },
            {
              id: "BE-ISSUE-2",
              iid: "2002",
              title: "Backend: Schema Migration",
              createdAt: "2025-01-05T00:00:00.000Z",
              closedAt: "2025-01-14T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/2002",
            },
            {
              id: "BE-ISSUE-3",
              iid: "2003",
              title: "Backend: Deployment Pipeline",
              createdAt: "2025-01-06T00:00:00.000Z",
              closedAt: "2025-01-15T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/2003",
            },
          ],
        })),

        // Ian–integrates frontend + backend and integrator-only issue
        {
          id: "ian",
          login: "ian",
          name: "Ian",
          avatarUrl:
            "https://ui-avatars.com/api/?name=Ian&background=random&color=fff",
          url: "https://example.com/ian",
          issues: [
            {
              id: "FE-ISSUE-1", // shared with frontend
              iid: "1001",
              title: "Frontend: Layout Overhaul",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-01-10T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/1001",
            },
            {
              id: "BE-ISSUE-1", // shared with backend
              iid: "2001",
              title: "Backend: API Design",
              createdAt: "2025-01-04T00:00:00.000Z",
              closedAt: "2025-01-13T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/2001",
            },
            {
              id: "INT-ISSUE-1",
              iid: "3001",
              title: "Integration: API-UI Sync",
              createdAt: "2025-01-07T00:00:00.000Z",
              closedAt: "2025-01-17T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/3001",
            },
          ],
        },

        // Iris integrates frontend + backend and integrator-only issue
        {
          id: "iris",
          login: "iris",
          name: "Iris",
          avatarUrl:
            "https://ui-avatars.com/api/?name=Iris&background=random&color=fff",
          url: "https://example.com/iris",
          issues: [
            {
              id: "FE-ISSUE-1", // shared with frontend
              iid: "1001",
              title: "Frontend: Layout Overhaul",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-01-10T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/1001",
            },
            {
              id: "BE-ISSUE-1", // shared with backend
              iid: "2001",
              title: "Backend: API Design",
              createdAt: "2025-01-04T00:00:00.000Z",
              closedAt: "2025-01-13T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/2001",
            },
            {
              id: "INT-ISSUE-2",
              iid: "3002",
              title: "Integration: Release Planning",
              createdAt: "2025-01-08T00:00:00.000Z",
              closedAt: "2025-01-18T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/3002",
            },
          ],
        },
      ];

      const scenario_c = [
        // Core cluster: Dev1–Dev5, heavily interconnected
        ...["Dev1", "Dev2", "Dev3", "Dev4", "Dev5"].map((name, i) => ({
          id: name.toLowerCase(),
          login: name.toLowerCase(),
          name,
          avatarUrl: `https://ui-avatars.com/api/?name=${name}&background=random&color=fff`,
          url: `https://example.com/${name.toLowerCase()}`,
          issues: [
            {
              id: "core-issue-1",
              iid: "4001",
              title: "Core Planning",
              description: "Tight-knit collaboration",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-01-10T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/4001",
            },
            {
              id: "core-issue-2",
              iid: "4002",
              title: "Sprint Review",
              description: "Tight-knit collaboration",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-01-11T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/4002",
            },
            {
              id: "core-issue-3",
              iid: "4003",
              title: "Refactor Planning",
              description: "Tight-knit collaboration",
              createdAt: "2025-01-03T00:00:00.000Z",
              closedAt: "2025-01-12T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/4003",
            },
          ].slice(0, 2 + (i % 2)), // Dev1,2,3 get 3 issues; 4,5 get 2
        })),

        // Peripheral devs: Dev6–Dev10, sparse 1:1 or 1:2 connections
        ...[
          { name: "Dev6", links: ["link-6-7"] },
          { name: "Dev7", links: ["link-6-7", "link-7-8"] },
          { name: "Dev8", links: ["link-7-8"] },
          { name: "Dev9", links: ["link-9-10"] },
          { name: "Dev10", links: ["link-9-10"] },
        ].map(({ name, links }) => ({
          id: name.toLowerCase(),
          login: name.toLowerCase(),
          name,
          avatarUrl: `https://ui-avatars.com/api/?name=${name}&background=random&color=fff`,
          url: `https://example.com/${name.toLowerCase()}`,
          issues: links.map((id, idx) => ({
            id,
            iid: `500${idx + name.charCodeAt(3)}`,
            title: `Sparse Issue ${id}`,
            description: "Peripheral connection",
            createdAt: `2025-01-1${idx}T00:00:00.000Z`,
            closedAt: `2025-01-2${idx}T00:00:00.000Z`,
            state: "open",
            webUrl: `https://example.com/issues/${id}`,
          })),
        })),

        // Loose triangle: Dev11–Dev13
        ...["Dev11", "Dev12", "Dev13"].map((name, idx) => ({
          id: name.toLowerCase(),
          login: name.toLowerCase(),
          name,
          avatarUrl: `https://ui-avatars.com/api/?name=${name}&background=random&color=fff`,
          url: `https://example.com/${name.toLowerCase()}`,
          issues: [
            {
              id: "triangle-1",
              iid: "6001",
              title: "Experimental API",
              description: "Loose shared work",
              createdAt: "2025-01-15T00:00:00.000Z",
              closedAt: "2025-01-18T00:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/6001",
            },
          ].concat(
            idx === 0
              ? []
              : [
                  {
                    id: "triangle-2",
                    iid: "6002",
                    title: "Sandbox Task",
                    description: "Cross-collaboration",
                    createdAt: "2025-01-19T00:00:00.000Z",
                    closedAt: "2025-01-21T00:00:00.000Z",
                    state: "open",
                    webUrl: "https://example.com/issues/6002",
                  },
                ],
          ),
        })),

        // Fully isolated: Dev14, Dev15
        ...["Dev14", "Dev15"].map((name) => ({
          id: name.toLowerCase(),
          login: name.toLowerCase(),
          name,
          avatarUrl: `https://ui-avatars.com/api/?name=${name}&background=random&color=fff`,
          url: `https://example.com/${name.toLowerCase()}`,
          issues: [],
        })),
      ];

      const accountsIssues: DataPluginAccount[] = [
        // 10 fully connected users
        {
          id: "user1",
          login: "user1",
          name: "User 1",
          avatarUrl: "https://example.com/avatar/user1.png",
          url: "https://example.com/user1",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user2",
          login: "user2",
          name: "User 2",
          avatarUrl: "https://example.com/avatar/user2.png",
          url: "https://example.com/user2",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user3",
          login: "user3",
          name: "User 3",
          avatarUrl: "https://example.com/avatar/user3.png",
          url: "https://example.com/user3",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user4",
          login: "user4",
          name: "User 4",
          avatarUrl: "https://example.com/avatar/user4.png",
          url: "https://example.com/user4",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user5",
          login: "user5",
          name: "User 5",
          avatarUrl: "https://example.com/avatar/user5.png",
          url: "https://example.com/user5",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user6",
          login: "user6",
          name: "User 6",
          avatarUrl: "https://example.com/avatar/user6.png",
          url: "https://example.com/user6",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user7",
          login: "user7",
          name: "User 7",
          avatarUrl: "https://example.com/avatar/user7.png",
          url: "https://example.com/user7",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user8",
          login: "user8",
          name: "User 8",
          avatarUrl: "https://example.com/avatar/user8.png",
          url: "https://example.com/user8",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user9",
          login: "user9",
          name: "User 9",
          avatarUrl: "https://example.com/avatar/user9.png",
          url: "https://example.com/user9",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        {
          id: "user10",
          login: "user10",
          name: "User 10",
          avatarUrl: "https://example.com/avatar/user10.png",
          url: "https://example.com/user10",
          issues: [
            {
              id: "ISSUE-FULL",
              iid: "100",
              title: "Fully-connected Issue",
              description: "This issue links all ten core users.",
              createdAt: "2025-01-01T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/100",
            },
            {
              id: "ISSUE-FULL-2",
              iid: "101",
              title: "Secondary Full Connectivity",
              description: "A second issue shared by the full clique.",
              createdAt: "2025-01-02T00:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/101",
            },
          ],
        },
        // 8 loosely connected users
        {
          id: "user11",
          login: "user11",
          name: "User 11",
          avatarUrl: "https://example.com/avatar/user11.png",
          url: "https://example.com/user11",
          issues: [
            {
              id: "ISSUE-L1",
              iid: "201",
              title: "Loose Cluster 1",
              description: "Links 11 & 12",
              createdAt: "2025-02-01T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/201",
            },
            {
              id: "ISSUE-L4",
              iid: "204",
              title: "Overlap Cluster A",
              description: "Links 11, 13, 17",
              createdAt: "2025-03-01T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/204",
            },
          ],
        },
        {
          id: "user12",
          login: "user12",
          name: "User 12",
          avatarUrl: "https://example.com/avatar/user12.png",
          url: "https://example.com/user12",
          issues: [
            {
              id: "ISSUE-L1",
              iid: "201",
              title: "Loose Cluster 1",
              description: "Links 11 & 12",
              createdAt: "2025-02-01T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/201",
            },
            {
              id: "ISSUE-L5",
              iid: "205",
              title: "Overlap Cluster B",
              description: "Links 12, 14, 18",
              createdAt: "2025-03-05T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/205",
            },
          ],
        },
        {
          id: "user13",
          login: "user13",
          name: "User 13",
          avatarUrl: "https://example.com/avatar/user13.png",
          url: "https://example.com/user13",
          issues: [
            {
              id: "ISSUE-L2",
              iid: "202",
              title: "Loose Cluster 2",
              description: "Links 13–15",
              createdAt: "2025-02-05T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/202",
            },
            {
              id: "ISSUE-L4",
              iid: "204",
              title: "Overlap Cluster A",
              description: "Links 11, 13, 17",
              createdAt: "2025-03-01T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/204",
            },
          ],
        },
        {
          id: "user14",
          login: "user14",
          name: "User 14",
          avatarUrl: "https://example.com/avatar/user14.png",
          url: "https://example.com/user14",
          issues: [
            {
              id: "ISSUE-L2",
              iid: "202",
              title: "Loose Cluster 2",
              description: "Links 13–15",
              createdAt: "2025-02-05T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/202",
            },
            {
              id: "ISSUE-L5",
              iid: "205",
              title: "Overlap Cluster B",
              description: "Links 12, 14, 18",
              createdAt: "2025-03-05T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/205",
            },
          ],
        },
        {
          id: "user15",
          login: "user15",
          name: "User 15",
          avatarUrl: "https://example.com/avatar/user15.png",
          url: "https://example.com/user15",
          issues: [
            {
              id: "ISSUE-L2",
              iid: "202",
              title: "Loose Cluster 2",
              description: "Links 13–15",
              createdAt: "2025-02-05T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/202",
            },
          ],
        },
        {
          id: "user16",
          login: "user16",
          name: "User 16",
          avatarUrl: "https://example.com/avatar/user16.png",
          url: "https://example.com/user16",
          issues: [
            {
              id: "ISSUE-L3",
              iid: "203",
              title: "Loose Cluster 3",
              description: "Links 16–18",
              createdAt: "2025-02-10T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/203",
            },
          ],
        },
        {
          id: "user17",
          login: "user17",
          name: "User 17",
          avatarUrl: "https://example.com/avatar/user17.png",
          url: "https://example.com/user17",
          issues: [
            {
              id: "ISSUE-L3",
              iid: "203",
              title: "Loose Cluster 3",
              description: "Links 16–18",
              createdAt: "2025-02-10T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/203",
            },
            {
              id: "ISSUE-L4",
              iid: "204",
              title: "Overlap Cluster A",
              description: "Links 11, 13, 17",
              createdAt: "2025-03-01T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/204",
            },
          ],
        },
        {
          id: "user18",
          login: "user18",
          name: "User 18",
          avatarUrl: "https://example.com/avatar/user18.png",
          url: "https://example.com/user18",
          issues: [
            {
              id: "ISSUE-L3",
              iid: "203",
              title: "Loose Cluster 3",
              description: "Links 16–18",
              createdAt: "2025-02-10T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/203",
            },
            {
              id: "ISSUE-L5",
              iid: "205",
              title: "Overlap Cluster B",
              description: "Links 12, 14, 18",
              createdAt: "2025-03-05T12:00:00.000Z",
              closedAt: "2025-03-05T12:00:00.000Z",
              state: "open",
              webUrl: "https://example.com/issues/205",
            },
          ],
        },
        // 2 alone users
        {
          id: "user19",
          login: "user19",
          name: "User 19",
          avatarUrl: "https://example.com/avatar/user19.png",
          url: "https://example.com/user19",
          issues: [],
        },
        {
          id: "user20",
          login: "user20",
          name: "User 20",
          avatarUrl: "https://example.com/avatar/user20.png",
          url: "https://example.com/user20",
          issues: [],
        },
      ];
      resolve(scenario_c); //scenario_a, scenario_b, scenario_c, accountsIssues
    });
  }
}
