import { DataPluginNote, DataPluginNotes } from '../../../interfaces/dataPluginInterfaces/dataPluginNote.ts';

export default class Notes implements DataPluginNotes {
  constructor() {}

  // this mock data is far from complete and could be more useful
  public async getAll(from: string, to: string) {
    console.log(`Getting Notes from ${from} to ${to}`);
    return new Promise<DataPluginNote[]>((resolve) => {
      const notes: DataPluginNote[] = [
        {
          body: 'added 10m of time spent',
          createdAt: '2022-04-28T12:35:37.891Z',
          updatedAt: '',
          issue: {
            id: '462684',
            iid: 1,
            title: 'Homescreen',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '1',
              gitSignature: 'tester@github.com',
            },
          },
        },
        {
          body: 'removed time spent',
          createdAt: '2022-04-28T12:48:10.885Z',
          updatedAt: '',
          issue: {
            id: '462684',
            iid: 1,
            title: 'Homescreen',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '1',
              gitSignature: 'tester@github.com',
            },
          },
        },
        {
          body: 'added 1h of time spent',
          createdAt: '2023-02-09T18:57:37.941Z',
          updatedAt: '',
          issue: {
            id: '460333',
            iid: 4,
            title: 'Meetings',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '1',
              gitSignature: 'tester@github.com',
            },
          },
        },
        {
          body: 'added 1h of time spent',
          createdAt: '2023-02-09T19:00:58.308Z',
          updatedAt: '',
          issue: {
            id: '460333',
            iid: 4,
            title: 'Meetings',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '2',
              gitSignature: 'tester2@github.com',
            },
          },
        },
        {
          body: 'added 1h 30m of time spent',
          createdAt: '2023-02-09T19:01:17.155Z',
          updatedAt: '',
          issue: {
            id: '460333',
            iid: 4,
            title: 'Meetings',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '2',
              gitSignature: 'tester2@github.com',
            },
          },
        },
        {
          body: 'added 30m of time spent',
          createdAt: '2023-02-09T19:01:25.497Z',
          updatedAt: '',
          issue: {
            id: '460333',
            iid: 4,
            title: 'Meetings',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '2',
              gitSignature: 'tester2@github.com',
            },
          },
        },
        {
          body: 'added 30m of time spent',
          createdAt: '2023-02-09T19:05:23.605Z',
          updatedAt: '',
          issue: {
            id: '460333',
            iid: 4,
            title: 'Meetings',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '1',
              gitSignature: 'tester@github.com',
            },
          },
        },
        {
          body: 'added 30m of time spent',
          createdAt: '2023-02-13T14:36:59.024Z',
          updatedAt: '',
          issue: {
            id: '459787',
            iid: 5,
            title: 'Backend update of xy',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '2',
              gitSignature: 'tester2@github.com',
            },
          },
        },
        {
          body: 'changed the description',
          createdAt: '2023-02-13T16:03:14.347Z',
          updatedAt: '',
          issue: {
            id: '459787',
            iid: 5,
            title: 'Backend update of xy',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '2',
              gitSignature: 'tester2@github.com',
            },
          },
        },
        {
          body: 'changed the description',
          createdAt: '2023-02-13T16:06:00.758Z',
          updatedAt: '',
          issue: {
            id: '459787',
            iid: 5,
            title: 'Backend update of xy',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '2',
              gitSignature: 'tester2@github.com',
            },
          },
        },
        {
          body: 'added 2h 30m of time spent',
          createdAt: '2023-02-14T21:13:51.066Z',
          updatedAt: '',
          issue: {
            id: '458767',
            iid: 6,
            title: 'Timetracking',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '1',
              gitSignature: 'tester@github.com',
            },
          },
        },
        {
          body: 'added 1h of time spent',
          createdAt: '2023-02-15T19:39:34.276Z',
          updatedAt: '',
          issue: {
            id: '459787',
            iid: 5,
            title: 'Backend update of xy',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '2',
              gitSignature: 'tester2@github.com',
            },
          },
        },
        {
          body: 'added 2h 30m of time spent',
          createdAt: '2023-02-15T19:39:47.189Z',
          updatedAt: '',
          issue: {
            id: '459787',
            iid: 5,
            title: 'Backend update of xy',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '2',
              gitSignature: 'tester2@github.com',
            },
          },
        },
        {
          body: 'added 1h of time spent',
          createdAt: '2023-02-15T22:50:59.816Z',
          updatedAt: '',
          issue: {
            id: '459787',
            iid: 5,
            title: 'Backend update of xy',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '2',
              gitSignature: 'tester2@github.com',
            },
          },
        },
        {
          body: 'added 1h of time spent',
          createdAt: '2023-04-03T17:06:37.756Z',
          updatedAt: '',
          issue: {
            id: '458094',
            iid: 7,
            title: 'update package.json',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '1',
              gitSignature: 'tester@github.com',
            },
          },
        },
        {
          body: 'added 2h of time spent',
          createdAt: '2023-04-03T17:07:16.529Z',
          updatedAt: '',
          issue: {
            id: '458094',
            iid: 7,
            title: 'update package.json',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '1',
              gitSignature: 'tester@github.com',
            },
          },
        },
        {
          body: 'added 30m of time spent',
          createdAt: '2023-04-04T14:17:37.467Z',
          updatedAt: '',
          issue: {
            id: '458767',
            iid: 6,
            title: 'Timetracking',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '1',
              gitSignature: 'tester@github.com',
            },
          },
        },
        {
          body: 'added 30m of time spent',
          createdAt: '2023-04-04T14:17:47.773Z',
          updatedAt: '',
          issue: {
            id: '460333',
            iid: 4,
            title: 'Meetings',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '2',
              gitSignature: 'tester2@github.com',
            },
          },
        },
        {
          body: 'subtracted 30m of time spent',
          createdAt: '2023-04-04T14:18:02.882Z',
          updatedAt: '',
          issue: {
            id: '458767',
            iid: 6,
            title: 'Timetracking',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '1',
              gitSignature: 'tester@github.com',
            },
          },
        },
        {
          body: 'added 30m of time spent',
          createdAt: '2023-04-04T14:18:18.146Z',
          updatedAt: '',
          issue: {
            id: '460333',
            iid: 4,
            title: 'Meetings',
            state: '',
            webUrl: '',
            createdAt: '',
            closedAt: '',
            author: {
              id: '1',
              name: 'Tester 1',
              user: {
                id: '2',
                gitSignature: 'tester2@github.com',
              },
            },
            assignee: null,
            assignees: [],
            notes: [],
          },
          mergeRequest: null,
          author: {
            id: '1',
            name: 'Tester 1',
            user: {
              id: '1',
              gitSignature: 'tester@github.com',
            },
          },
        },
      ];
      resolve(notes);
    });
  }
}
